spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dormitoryms?useSSL=false
    username: root
    password: hsp
    driver-class-name: com.mysql.jdbc.Driver
    # 关闭自定义配置druid,使用starter配置
    # filters: stat,wall
    # max-active: 12

    # 使用starter配置druid
    druid:
      # 这个包下的所有内容进行监控,监控SpringBean
      aop-patterns: com.atguigu.admin.*
      # 开启防火墙监控，注意这里是filters（有s）.stat是sql监控，wall是防火墙功能
      filters: stat,wall,slf4j

      # 配置druid的监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        # 失效重置按钮
        reset-enable: false

      # 采集web-jdbc关联监控的数据
      web-stat-filter:
        enabled: true
        exclusions: '*.js,*.gif,*.jpg,*png,*.css,*.ico,/druid/*'
        url-pattern: '/*'

      # 对上面filters中的具体参数进行设定
      filter:
        stat:
          # 设定查询超过1000s的都是慢查询
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

  jdbc:
    template:
      # 1000秒内未查询出数据就认为数据超时
      query-timeout: 1000
  redis:
    host: localhost
    port: 6379
    password:
    # 使用lettuce对pool的配置：
    lettuce:
      pool:
        max-active: 10
    # 当想要使用jedis时，在配置文件中明确声明使用jedis
    client-type: jedis
    # 使用jedis对pool的配置
    jedis:
      pool:
        max-active: 10



# 配置mybatis规则
mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 一旦在这里使用configuration对mybatis进行定义，
  # config-location: classpath:mybatis/mybatis-config.xml将不能存在，否则不知道按哪个去配置文件
  configuration:
    # 开启驼峰命名：当数据库有user_id这样的参数，开启后会自动匹配java中的userId参数
    # 法一：mybatis的配置文件中配
    map-underscore-to-camel-case: true

# management是所有actuator的配置
management:
  endpoints:
    # 默认关闭所有监控端点
    enabled-by-default: false
    web:
      exposure:
        # 以web方式暴露所有端点
        include: '*'
  endpoint:
    health:
      # 总是显示详细信息
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true
